# Cloud Build configuration for automatic deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sistema-planes:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sistema-planes:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'evaluacion-desempeno-inter'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sistema-planes:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '2'
      - '--min-instances'
      - '0'
      - '--port'
      - '8080'
      - '--add-cloudsql-instances'
      - 'appsindunnova:us-central1:postgres-consolidated'
      - '--set-env-vars'
      - 'DJANGO_SETTINGS_MODULE=config.settings_production,DB_ENGINE=django.db.backends.postgresql,DB_NAME=evaluacion_desempeno_inter,DB_USER=postgres,DB_PASSWORD=AppsIndunnova2025!,DB_HOST=/cloudsql/appsindunnova:us-central1:postgres-consolidated,DB_PORT=5432'

images:
  - 'gcr.io/$PROJECT_ID/sistema-planes:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY