# Generated by Django 5.0 on 2025-08-29 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50, verbose_name='Período')),
                ('puntaje', models.IntegerField(verbose_name='Puntaje')),
                ('fecha', models.DateField(verbose_name='Fecha de Evaluación')),
                ('puntaje_calidad', models.IntegerField(default=0, verbose_name='Calidad')),
                ('puntaje_entrega', models.IntegerField(default=0, verbose_name='Entrega')),
                ('puntaje_documentacion', models.IntegerField(default=0, verbose_name='Documentación')),
                ('puntaje_precio', models.IntegerField(default=0, verbose_name='Precio')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PlanMejoramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('EN_REVISION', 'En Revisión'), ('REQUIERE_AJUSTES', 'Requiere Ajustes'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('analisis_causa', models.TextField(verbose_name='Análisis de Causa Raíz')),
                ('acciones_propuestas', models.TextField(verbose_name='Acciones Propuestas')),
                ('responsable', models.CharField(max_length=200, verbose_name='Responsable')),
                ('fecha_implementacion', models.DateField(verbose_name='Fecha de Implementación')),
                ('indicadores_seguimiento', models.TextField(verbose_name='Indicadores de Seguimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('comentarios_tecnico', models.TextField(blank=True, verbose_name='Comentarios del Técnico')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('numero_version', models.IntegerField(default=1)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='planes.evaluacion')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de Mejoramiento',
                'verbose_name_plural': 'Planes de Mejoramiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='Estado Nuevo')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='planes.planmejoramiento')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='planes/documentos/%Y/%m/', verbose_name='Archivo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Documento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='planes.planmejoramiento')),
            ],
            options={
                'verbose_name': 'Documento del Plan',
                'verbose_name_plural': 'Documentos del Plan',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='AccionMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Acción')),
                ('responsable', models.CharField(max_length=200, verbose_name='Responsable')),
                ('fecha_compromiso', models.DateField(verbose_name='Fecha Compromiso')),
                ('indicador', models.CharField(max_length=500, verbose_name='Indicador de Éxito')),
                ('completado', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='planes.planmejoramiento')),
            ],
            options={
                'verbose_name': 'Acción de Mejora',
                'verbose_name_plural': 'Acciones de Mejora',
                'ordering': ['fecha_compromiso'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
            },
        ),
        migrations.AddField(
            model_name='planmejoramiento',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_mejoramiento', to='planes.proveedor'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='planes.proveedor'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together={('proveedor', 'periodo')},
        ),
    ]
