# Generated by Django 5.0 on 2025-09-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='telefono',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email_adicional',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Adicional del Gestor del Proyecto'),
        ),
        migrations.AlterField(
            model_name='planmejoramiento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('FIRMADO_ENVIADO', 'Firmado y Enviado'), ('EN_REVISION', 'En Revisión'), ('REQUIERE_AJUSTES', 'Requiere Ajustes'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20, verbose_name='Estado'),
        ),
    ]
