# Generated by Django 5.0 on 2025-09-22 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_hacer_user_opcional_en_proveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='puntaje_documentacion',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='puntaje_entrega',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='puntaje_precio',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_limite_aclaracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Límite de Aclaración'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_limite_plan',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Límite Plan'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='max_ambiental_social',
            field=models.IntegerField(default=25, verbose_name='Máximo Ambiental y Social'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='max_calidad',
            field=models.IntegerField(default=25, verbose_name='Máximo Calidad'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='max_gestion',
            field=models.IntegerField(default=25, verbose_name='Máximo Gestión'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='max_oportunidad',
            field=models.IntegerField(default=25, verbose_name='Máximo Oportunidad'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='max_sst',
            field=models.IntegerField(default=25, verbose_name='Máximo SST'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Contrato/Orden'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='observaciones_ambiental_social',
            field=models.TextField(blank=True, verbose_name='Observaciones Ambiental y Social'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='observaciones_calidad',
            field=models.TextField(blank=True, verbose_name='Observaciones Calidad'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='observaciones_generales',
            field=models.TextField(blank=True, verbose_name='Observaciones Generales'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='observaciones_gestion',
            field=models.TextField(blank=True, verbose_name='Observaciones Gestión'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='observaciones_oportunidad',
            field=models.TextField(blank=True, verbose_name='Observaciones Oportunidad'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='observaciones_sst',
            field=models.TextField(blank=True, verbose_name='Observaciones SST'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='puntaje_ambiental_social',
            field=models.IntegerField(default=0, verbose_name='Ambiental y Social'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='puntaje_gestion',
            field=models.IntegerField(default=0, verbose_name='Gestión'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='puntaje_oportunidad',
            field=models.IntegerField(default=0, verbose_name='Oportunidad'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='puntaje_sst',
            field=models.IntegerField(default=0, verbose_name='Seguridad y Salud en el Trabajo'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='requiere_aprobacion_ambiental',
            field=models.BooleanField(default=False, verbose_name='Requiere Aprobación Ambiental'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='requiere_aprobacion_sst',
            field=models.BooleanField(default=False, verbose_name='Requiere Aprobación SST'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='subcategoria',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subcategoría'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Asignado'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='periodo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_anterior',
            field=models.CharField(max_length=30, verbose_name='Estado Anterior'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_nuevo',
            field=models.CharField(max_length=30, verbose_name='Estado Nuevo'),
        ),
        migrations.AlterField(
            model_name='planmejoramiento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('FIRMADO_ENVIADO', 'Firmado y Enviado'), ('EN_REVISION', 'En Revisión'), ('ESPERANDO_APROBACION', 'Esperando Aprobación'), ('SOLICITUD_AJUSTES', 'Solicitud de Ajustes'), ('REQUIERE_AJUSTES', 'Requiere Ajustes'), ('DOCUMENTOS_REEVALUADOS', 'Documentos Reevaluados'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=30, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_perfil', models.CharField(choices=[('TECNICO', 'Técnico'), ('PROVEEDOR', 'Proveedor'), ('GESTOR', 'Gestor de Planes de Mejoramiento')], default='PROVEEDOR', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('requiere_cambio_password', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
