# Generated by Django 4.2.11 on 2025-10-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0004_agregar_perfiles_y_campos_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo_perfil',
            field=models.CharField(choices=[('TECNICO', 'Técnico'), ('PROVEEDOR', 'Proveedor'), ('GESTOR', 'Gestor de Planes de Mejoramiento'), ('GESTOR_COMPRAS', 'Gestor de Compras')], default='PROVEEDOR', max_length=20),
        ),
    ]
