# Generated by Django 4.2.11 on 2025-10-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0005_alter_perfilusuario_tipo_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('OBRA', 'Obra'), ('SUMINISTRO', 'Suministro'), ('SERVICIO', 'Servicio'), ('CONSULTORIA', 'Consultoría'), ('INTERVENTORIA', 'Interventoría'), ('ORDEN_COMPRA', 'Orden de Compra'), ('OTRO', 'Otro')], max_length=20, null=True, verbose_name='Tipo de Contrato'),
        ),
    ]
