# Generated by Django 4.2.11 on 2025-10-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0006_evaluacion_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('OBRA', 'Obra'), ('SUMINISTRO', 'Suministro'), ('SERVICIO', 'Prestación de Servicios'), ('CONSULTORIA', 'Consultoría'), ('INTERVENTORIA', 'Interventoría'), ('ORDEN_COMPRA', 'Orden de Compra'), ('OBRAS_CIVILES', 'Obras Civiles'), ('SUMINISTRO_EQUIPOS', 'Suministro de Equipos'), ('MONTAJE_ELECTROMECANICO', 'Montaje Electromecánico'), ('SERVICIOS_TECNICOS', 'Servicios Técnicos Especializados'), ('MANTENIMIENTO', 'Mantenimiento'), ('ESTUDIOS_DISENOS', 'Estudios y Diseños'), ('TRANSPORTE', 'Transporte'), ('OTRO', 'Otro')], max_length=30, null=True, verbose_name='Tipo de Contrato'),
        ),
    ]
