# Generated by Django 4.2.11 on 2025-10-08 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planes', '0007_actualizar_tipos_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('PLAN_MEJORAMIENTO', 'Plan de Mejoramiento'), ('ANALISIS_CAUSA_RAIZ', 'Análisis de Causa Raíz'), ('OTRO', 'Otro')], default='OTRO', max_length=30, verbose_name='Tipo de Documento')),
                ('archivo', models.FileField(upload_to='planes_adjuntos/%Y/%m/', verbose_name='Archivo')),
                ('nombre_original', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Archivo')),
                ('descripcion', models.CharField(blank=True, max_length=500, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='planes.planmejoramiento', verbose_name='Plan de Mejoramiento')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Adjunto del Plan',
                'verbose_name_plural': 'Adjuntos del Plan',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
