# Generated by Django 5.2.7 on 2025-10-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0009_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmejoramiento',
            name='carta_evaluacion',
            field=models.FileField(blank=True, null=True, upload_to='cartas_evaluacion/%Y/%m/', verbose_name='Carta de Evaluación CS'),
        ),
        migrations.AddField(
            model_name='planmejoramiento',
            name='dias_sin_respuesta',
            field=models.IntegerField(default=0, verbose_name='Días sin Respuesta'),
        ),
        migrations.AddField(
            model_name='planmejoramiento',
            name='fecha_aclaracion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aclaración'),
        ),
        migrations.AddField(
            model_name='planmejoramiento',
            name='fecha_carta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Envío Carta'),
        ),
        migrations.AddField(
            model_name='planmejoramiento',
            name='fecha_radicacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Radicación'),
        ),
        migrations.AddField(
            model_name='planmejoramiento',
            name='fecha_suspension',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Suspensión'),
        ),
        migrations.AddField(
            model_name='planmejoramiento',
            name='motivo_rechazo',
            field=models.TextField(blank=True, verbose_name='Motivo de Rechazo'),
        ),
        migrations.AddField(
            model_name='planmejoramiento',
            name='numero_radicado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Radicado'),
        ),
        migrations.AddField(
            model_name='planmejoramiento',
            name='observaciones_aclaracion',
            field=models.TextField(blank=True, verbose_name='Observaciones de Aclaración'),
        ),
        migrations.AddField(
            model_name='planmejoramiento',
            name='proveedor_suspendido',
            field=models.BooleanField(default=False, verbose_name='Proveedor Suspendido por Falta de Ética'),
        ),
        migrations.AlterField(
            model_name='planmejoramiento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('PROCESO_FIRMAS', 'Proceso de Firmas'), ('FIRMADO_ENVIADO', 'Firmado y Enviado'), ('ESPERANDO_APROBACION', 'Esperando Aprobación'), ('EN_RADICACION', 'En Radicación'), ('PM_RADICADO', 'PM Radicado'), ('PM_REEVALUADO', 'PM Reevaluado'), ('NO_RECIBIDO', 'No Recibido'), ('ACLARACION', 'Aclaración'), ('EP_REEVALUADO', 'EP Reevaluado'), ('SOLICITUD_AJUSTES', 'Solicitud de Ajustes'), ('REQUIERE_AJUSTES', 'Requiere Ajustes'), ('RECHAZADO', 'Rechazado'), ('CANCELACION_RADICADA', 'Cancelación Radicada'), ('FALTA_ETICA', 'Falta de Ética'), ('EN_REVISION', 'En Revisión'), ('DOCUMENTOS_REEVALUADOS', 'Documentos Reevaluados'), ('APROBADO', 'Aprobado'), ('FIN', 'Fin')], default='BORRADOR', max_length=30, verbose_name='Estado'),
        ),
    ]
