# Generated by Django 5.2.7 on 2025-10-20 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0010_planmejoramiento_carta_evaluacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Calificación',
                'verbose_name_plural': 'Tipos de Calificación',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sap', models.IntegerField(verbose_name='ID SAP')),
                ('descripcion_criterio', models.CharField(max_length=500, verbose_name='Descripción del Criterio')),
                ('id_criterio', models.IntegerField(verbose_name='ID Criterio')),
                ('respuesta_normal', models.TextField(verbose_name='Respuesta Normal')),
                ('respuesta_corta', models.CharField(max_length=500, verbose_name='Respuesta Corta')),
                ('sociedad', models.CharField(default='ISA', max_length=50, verbose_name='Sociedad')),
                ('puntuacion_maxima', models.IntegerField(verbose_name='Puntuación Máxima')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de Presentación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo_calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='planes.tipocalificacion', verbose_name='Tipo de Calificación')),
            ],
            options={
                'verbose_name': 'Criterio de Evaluación',
                'verbose_name_plural': 'Criterios de Evaluación',
                'ordering': ['tipo_calificacion', 'id_criterio', 'orden'],
                'unique_together': {('id_sap', 'tipo_calificacion', 'id_criterio', 'puntuacion_maxima')},
            },
        ),
    ]
