# Generated by Django 5.2.7 on 2025-10-20 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0011_tipocalificacion_criterioevaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_criterio', models.IntegerField(verbose_name='ID Criterio')),
                ('puntuacion_obtenida', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puntuación Obtenida')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='planes.criterioevaluacion', verbose_name='Criterio Seleccionado')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='planes.evaluacion', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Respuesta de Evaluación',
                'verbose_name_plural': 'Respuestas de Evaluación',
                'ordering': ['evaluacion', 'id_criterio'],
                'unique_together': {('evaluacion', 'id_criterio')},
            },
        ),
    ]
