# Generated by Django 5.2.7 on 2025-10-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0012_respuestaevaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmejoramiento',
            name='archivo_acciones_propuestas',
            field=models.FileField(blank=True, null=True, upload_to='planes_mejoramiento/acciones/%Y/%m/', verbose_name='Archivo Acciones Propuestas'),
        ),
        migrations.AddField(
            model_name='planmejoramiento',
            name='archivo_analisis_causa',
            field=models.FileField(blank=True, null=True, upload_to='planes_mejoramiento/analisis/%Y/%m/', verbose_name='Archivo Análisis de Causa Raíz'),
        ),
        migrations.AddField(
            model_name='planmejoramiento',
            name='archivo_indicadores',
            field=models.FileField(blank=True, null=True, upload_to='planes_mejoramiento/indicadores/%Y/%m/', verbose_name='Archivo Indicadores de Seguimiento'),
        ),
        migrations.AddField(
            model_name='planmejoramiento',
            name='archivo_otros',
            field=models.FileField(blank=True, null=True, upload_to='planes_mejoramiento/otros/%Y/%m/', verbose_name='Otros Archivos Adjuntos'),
        ),
    ]
