# Generated by Django 5.2.7 on 2025-10-20 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0013_planmejoramiento_archivo_acciones_propuestas_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='criterioevaluacion',
            unique_together={('id_sap', 'tipo_calificacion', 'id_criterio', 'puntuacion_maxima', 'sociedad')},
        ),
    ]
