# Generated by Django 5.2.7 on 2025-11-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0014_actualizar_unique_together_criterios'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='estado_firma',
            field=models.CharField(choices=[('PROCESO_FIRMAS', 'Proceso de Firmas'), ('FIRMADO', 'Firmado y Enviado'), ('CANCELADO', 'Cancelado'), ('CAMBIO_NOTAS', 'Cambio de Notas')], default='PROCESO_FIRMAS', max_length=20, verbose_name='Estado del Proceso de Firmas'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_cambio_estado_firma',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cambio de Estado de Firma'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='observaciones_firma',
            field=models.TextField(blank=True, verbose_name='Observaciones del Proceso de Firmas'),
        ),
    ]
