# Generated by Django 5.2.7 on 2025-11-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0015_evaluacion_estado_firma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_envio_notificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío de Notificación al Proveedor'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='resumen_notificacion',
            field=models.TextField(blank=True, verbose_name='Resumen de la Notificación Enviada'),
        ),
    ]
