# Generated by Django 5.2.7 on 2025-11-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0016_evaluacion_fecha_envio_notificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='estado_flujo_evaluacion',
            field=models.CharField(choices=[('FLUJO_NORMAL', 'Flujo Normal'), ('FALTA_ETICA', 'Falta de Ética'), ('ACLARACION', 'Aclaración Solicitada'), ('REEVALUADO', 'Reevaluado')], default='FLUJO_NORMAL', max_length=20, verbose_name='Estado del Flujo de Evaluación'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_cambio_estado_flujo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cambio de Estado de Flujo'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_reevaluacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Reevaluación'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='observaciones_flujo',
            field=models.TextField(blank=True, verbose_name='Observaciones del Flujo de Evaluación'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='puntaje_reevaluacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Puntaje de Reevaluación'),
        ),
    ]
