# Generated by Django 5.2.7 on 2025-11-14 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0017_evaluacion_estado_flujo_evaluacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambioCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100, verbose_name='Campo modificado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor nuevo')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios_campos', to='planes.planmejoramiento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio')),
            ],
            options={
                'verbose_name': 'Historial de Cambio de Campo',
                'verbose_name_plural': 'Historial de Cambios de Campos',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
