# Generated by Django 5.0 on 2025-12-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0018_historialcambiocampo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='sociedad',
            field=models.CharField(blank=True, choices=[('ISA', 'ISA'), ('ITCO', 'ITCO'), ('TRANSELCA', 'TRANSELCA')], max_length=20, null=True, verbose_name='Sociedad'),
        ),
    ]
