# Generated by Django 5.0 on 2025-12-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0019_add_sociedad_to_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='observaciones_tecnico',
            field=models.TextField(blank=True, verbose_name='Observaciones del Técnico'),
        ),
    ]
